version: "3.8"

services:
  api:
    build: .
    ports:
      - "127.0.0.1:8000:80"
    environment:
      PG_DSN: postgres://postgres:password@db:5432/postgres

  db:
    image: postgis/postgis:15-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5442:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
